services:
  fastapi:
    image: mlops
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  streamlit:
    image: streamlit
    build:
      context: ./streamlit_app/
      dockerfile: ./streamlit_app.Dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://fastapi:8000

